#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd. Your script should only display: username, user id, Home directory path for the user using while loop
while IFS= read -r line
do
	echo "$line" | cut -f 1,3,6 -d ':'
done < "/etc/passwd" 
