#!/usr/bin/env bash
# Bash script that loops from 1 to 10, display bad luck in 4th loop and good luck in 8th loop using while loop and if, elif and else statements
x=1
while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else

	fi
	((x++))
done
